//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagesearchengineservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Email { get; set; }
        public long User_Mobile_No { get; set; }
        public string User_Password { get; set; }
        public string User_Status { get; set; }
    }
}
